version: '3.9'

services:
  postgres:
    networks:
      net: null
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aboba
      POSTGRES_PASSWORD: aboba
      POSTGRES_DB: registration
    restart: always
    healthcheck:
      test: pg_isready -U aboba -d registration
      interval: 3s
      retries: 5
  tests:
    networks:
      net: null
    container_name: tests
    build:
      context: ../python_tests/code
    volumes:
      - ../python_tests/code:/tmp/code
    entrypoint: /bin/bash /tmp/code/start_tests.sh
    environment:
      - POSTGRES_USER=aboba
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=aboba
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_started
      selenoid:
        condition: service_started
  app:
    networks:
      net: null
    ports:
      - "8080:8080"
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
      selenoid:
        condition: service_started
    container_name: app
    environment:
      - spring.application.name=registration
      - spring.datasource.url=jdbc:postgresql://postgres:5432/registration
      - spring.datasource.username=aboba
      - spring.datasource.password=aboba
      - server.port=8080
      - spring.freemarker.expose-request-attributes=true
      - spring.jpa.hibernate.ddl-auto=create-drop
      - spring.jackson.serialization.indent_output=true
      - server.error.include-message=always
      - spring.web.resources.add-mappings=true
  selenoid:
    container_name: selenoid
    networks:
      net: null
    image: "aerokube/selenoid:1.10.7"
    volumes:
      - ../python_tests/code/config:/etc/browser
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "-conf", "/etc/browser/browsers.json", "-container-network", "net" ]
  selenoid-chrome:
    container_name: selenoid-chrome
    image: "selenoid/chrome:98.0"
networks:
  net:
    external:
      name: net
