version: '3.9'

services:
  postgres:
    container_name: users_container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aboba
      POSTGRES_PASSWORD: aboba
      POSTGRES_DB: registration
    restart: always
