name: kekis

on:
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker compose
        run: docker compose --project-directory registration up -d
