name: kekis

on:
  push:
    branches: ["main"]
  
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create docker network
        run: docker network create net
      - name: build docker compose
        run: docker compose --project-directory registration up -d
